[[dependencies]]
name = "addr2line"
version = "0.21.0"
description = "A cross-platform symbolication library written in Rust, using `gimli`"
license = "Apache-2.0 OR MIT"
notices = ["Copyright (c) 2016-2018 The gimli Developers"]
repository = "https://github.com/gimli-rs/addr2line"

[[dependencies]]
name = "adler"
version = "1.0.2"
description = "A simple clean-room implementation of the Adler-32 checksum"
license = "0BSD OR MIT OR Apache-2.0"
notices = ["Copyright (C) Jonas Schievink <jonasschievink@gmail.com>"]
authors = ["Jonas Schievink <jonasschievink@gmail.com>"]
repository = "https://github.com/jonas-schievink/adler.git"

[[dependencies]]
name = "backtrace"
version = "0.3.69"
description = """
A library to acquire a stack trace (backtrace) at runtime in a Rust program.
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["The Rust Project Developers"]
repository = "https://github.com/rust-lang/backtrace-rs"

[[dependencies]]
name = "cc"
version = "1.0.83"
description = """
A build-time dependency for Cargo build scripts to assist in invoking the native
C compiler to compile native C code into a static archive to be linked into Rust
code.
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["Alex Crichton <alex@alexcrichton.com>"]
repository = "https://github.com/rust-lang/cc-rs"

[[dependencies]]
name = "cfg-if"
version = "1.0.0"
description = """
A macro to ergonomically define an item depending on a large number of #[cfg]
parameters. Structured like an if-else chain, the first matching branch is the
item that gets emitted.
"""
license = "MIT/Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["Alex Crichton <alex@alexcrichton.com>"]
repository = "https://github.com/alexcrichton/cfg-if"

[[dependencies]]
name = "color-eyre"
version = "0.6.2"
description = "An error report handler for panics and eyre::Reports for colorful, consistent, and well formatted error reports for all kinds of errors."
license = "MIT OR Apache-2.0"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
repository = "https://github.com/yaahc/color-eyre"

[[dependencies]]
name = "color-spantrace"
version = "0.2.1"
description = "A pretty printer for tracing_error::SpanTrace based on color-backtrace"
license = "MIT OR Apache-2.0"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
repository = "https://github.com/eyre-rs/eyre"

[[dependencies]]
name = "either"
version = "1.9.0"
description = """
The enum `Either` with variants `Left` and `Right` is a general purpose sum type with two cases.
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015"]
authors = ["bluss"]
repository = "https://github.com/bluss/either"

[[dependencies]]
name = "eyre"
version = "0.6.11"
description = "Flexible concrete Error Reporting type built on std::error::Error with customizable Reports"
license = "MIT OR Apache-2.0"
authors = [
    "David Tolnay <dtolnay@gmail.com>",
    "Jane Lusby <jlusby42@gmail.com>",
]
repository = "https://github.com/eyre-rs/eyre"

[[dependencies]]
name = "gimli"
version = "0.28.1"
description = "A library for reading and writing the DWARF debugging format."
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015 The Rust Project Developers"]
repository = "https://github.com/gimli-rs/gimli"

[[dependencies]]
name = "indenter"
version = "0.3.3"
description = """
A formatter wrapper that indents the text, designed for error display impls
"""
license = "MIT OR Apache-2.0"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
repository = "https://github.com/yaahc/indenter"

[[dependencies]]
name = "itertools"
version = "0.12.0"
description = "Extra iterator adaptors, iterator methods, free functions, and macros."
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2015"]
authors = ["bluss"]
repository = "https://github.com/rust-itertools/itertools"

[[dependencies]]
name = "lazy_static"
version = "1.4.0"
description = "A macro for declaring lazily evaluated statics in Rust."
license = "MIT/Apache-2.0"
notices = ["Copyright (c) 2010 The Rust Project Developers"]
authors = ["Marvin Löbel <loebel.marvin@gmail.com>"]
repository = "https://github.com/rust-lang-nursery/lazy-static.rs"

[[dependencies]]
name = "libc"
version = "0.2.152"
description = """
Raw FFI bindings to platform libraries like libc.
"""
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2014-2020 The Rust Project Developers"]
authors = ["The Rust Project Developers"]
repository = "https://github.com/rust-lang/libc"

[[dependencies]]
name = "memchr"
version = "2.7.1"
description = """
Provides extremely fast (uses SIMD on x86_64, aarch64 and wasm32) routines for
1, 2 or 3 byte search and single substring search.
"""
license = "Unlicense OR MIT"
notices = ["Copyright (c) 2015 Andrew Gallant"]
authors = [
    "Andrew Gallant <jamslam@gmail.com>",
    "bluss",
]
repository = "https://github.com/BurntSushi/memchr"

[[dependencies]]
name = "miniz_oxide"
version = "0.7.1"
description = "DEFLATE compression and decompression library rewritten in Rust based on miniz"
license = "MIT OR Zlib OR Apache-2.0"
notices = [
    "Copyright (c) 2017 Frommi",
    "Copyright (c) 2020 Frommi",
]
authors = [
    "Frommi <daniil.liferenko@gmail.com>",
    "oyvindln <oyvindln@users.noreply.github.com>",
]
repository = "https://github.com/Frommi/miniz_oxide/tree/master/miniz_oxide"

[[dependencies]]
name = "object"
version = "0.32.2"
description = "A unified interface for reading and writing object file formats."
license = "Apache-2.0 OR MIT"
notices = ["Copyright (c) 2015 The Gimli Developers"]
repository = "https://github.com/gimli-rs/object"

[[dependencies]]
name = "once_cell"
version = "1.19.0"
description = "Single assignment cells and lazy values."
license = "MIT OR Apache-2.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/matklad/once_cell"

[[dependencies]]
name = "owo-colors"
version = "3.5.0"
description = "Zero-allocation terminal colors that'll make people go owo"
license = "MIT"
notices = ["Copyright (c) 2020 - present The owo-colors Developers"]
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
repository = "https://github.com/jam1garner/owo-colors"

[[dependencies]]
name = "pin-project-lite"
version = "0.2.13"
description = """
A lightweight version of pin-project written with declarative macros.
"""
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/pin-project-lite"

[[dependencies]]
name = "rustc-demangle"
version = "0.1.23"
description = """
Rust compiler symbol demangling.
"""
license = "MIT/Apache-2.0"
notices = ["Copyright (c) 2014 Alex Crichton"]
authors = ["Alex Crichton <alex@alexcrichton.com>"]
repository = "https://github.com/alexcrichton/rustc-demangle"

[[dependencies]]
name = "sharded-slab"
version = "0.1.7"
description = """
A lock-free concurrent slab.
"""
license = "MIT"
notices = ["Copyright (c) 2019 Eliza Weisman"]
authors = ["Eliza Weisman <eliza@buoyant.io>"]
repository = "https://github.com/hawkw/sharded-slab"

[[dependencies]]
name = "tap"
version = "1.0.1"
description = "Generic extensions for tapping values in Rust"
license = "MIT"
notices = ["Copyright (c) 2017 Elliot Linder <darfink@gmail.com>"]
authors = [
    "Elliott Linder <elliott.darfink@gmail.com>",
    "myrrlyn <self@myrrlyn.dev>",
]
repository = "https://github.com/myrrlyn/tap"

[[dependencies]]
name = "thread_local"
version = "1.1.7"
description = "Per-object thread-local storage"
license = "MIT OR Apache-2.0"
notices = ["Copyright (c) 2016 The Rust Project Developers"]
authors = ["Amanieu d'Antras <amanieu@gmail.com>"]
repository = "https://github.com/Amanieu/thread_local-rs"

[[dependencies]]
name = "tracing"
version = "0.1.40"
description = """
Application-level tracing for Rust.
"""
license = "MIT"
notices = ["Copyright (c) 2019 Tokio Contributors"]
authors = [
    "Eliza Weisman <eliza@buoyant.io>",
    "Tokio Contributors <team@tokio.rs>",
]
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"

[[dependencies]]
name = "tracing-core"
version = "0.1.32"
description = """
Core primitives for application-level tracing.
"""
license = "MIT"
notices = ["Copyright (c) 2019 Tokio Contributors"]
authors = ["Tokio Contributors <team@tokio.rs>"]
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"

[[dependencies]]
name = "tracing-error"
version = "0.2.0"
description = """
Utilities for enriching errors with `tracing`.
"""
license = "MIT"
notices = ["Copyright (c) 2019 Tokio Contributors"]
authors = [
    "Eliza Weisman <eliza@buoyant.io>",
    "Jane Lusby <jlusby@yaah.dev>",
    "Tokio Contributors <team@tokio.rs>",
]
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"

[[dependencies]]
name = "tracing-subscriber"
version = "0.3.18"
description = """
Utilities for implementing and composing `tracing` subscribers.
"""
license = "MIT"
notices = ["Copyright (c) 2019 Tokio Contributors"]
authors = [
    "Eliza Weisman <eliza@buoyant.io>",
    "David Barsky <me@davidbarsky.com>",
    "Tokio Contributors <team@tokio.rs>",
]
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"

[[dependencies]]
name = "valuable"
version = "0.1.0"
description = """
Object-safe value inspection, used to pass un-typed structured data across trait-object boundaries.
"""
license = "MIT"
repository = "https://github.com/tokio-rs/valuable"
